ALTER TABLE `QUESTIONS` DROP FOREIGN KEY `fk_QUESTIONS_1`;

-- AlterTable
ALTER TABLE `User` MODIFY `user_id` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `QUESTIONS` ADD CONSTRAINT `fk_QUESTIONS_1` FOREIGN KEY (`user_id`) REFERENCES `User`(`user_id`) ON DELETE CASCADE ON UPDATE RESTRICT;