ALTER TABLE `QUESTIONS` DROP FOREIGN KEY `fk_QUESTIONS_1`;

-- AlterTable
ALTER TABLE `USERS` MODIFY `user_id` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `QUESTIONS` ADD CONSTRAINT `fk_QUESTIONS_1` FOREIGN KEY (`user_id`) REFERENCES `USERS`(`user_id`) ON DELETE CASCADE ON UPDATE RESTRICT;